spring:
  application:
    name: api.cadastro.pessoa

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cadastro_db
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
